<?php

/*
 * This file is part of aaplusplus.
 *
 * (c) 2019 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace AppBundle\Entity\BelysningTiltagDetail;

use Doctrine\ORM\EntityRepository;

/**
 * ErstatningsLyskildeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErstatningsLyskildeRepository extends EntityRepository
{
    /**
     * Check if entity can be removed (deleted). If not, return an error message.
     *
     * @return null|string
     */
    public function getRemoveErrorMessage(ErstatningsLyskilde $erstatningsLyskilde)
    {
        $query = $this->_em->createQuery('SELECT d FROM AppBundle:BelysningTiltagDetail d WHERE d.erstatningsLyskilde = :erstatningsLyskilde');
        $query->setParameter('erstatningsLyskilde', $erstatningsLyskilde);
        $result = $query->getResult();

        if ($result) {
            return 'erstatningslyskilde.error.in_use';
        }

        return null;
    }
}
