<?php

/*
 * This file is part of aaplusplus.
 *
 * (c) 2019 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace AppBundle\Entity\BelysningTiltagDetail;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * BelysningTiltagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NyStyringRepository extends EntityRepository
{
    /**
     * Initializes a new <tt>EntityRepository</tt>.
     *
     * @param EntityManager         $em    the EntityManager to use
     * @param Mapping\ClassMetadata $class the class descriptor
     */
    public function __construct($em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }

    public function findActive()
    {
        $query = $this->_em->createQuery("SELECT ns FROM AppBundle:BelysningTiltagDetail\NyStyring ns WHERE ns.deactivatedAt IS NULL");

        return $query->getResult();
    }
}
