<?php

/*
 * This file is part of aaplusplus.
 *
 * (c) 2019 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace AppBundle\Entity\TekniskIsoleringTiltagDetail;

use Doctrine\ORM\EntityRepository;

/**
 * KomponentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomponentRepository extends EntityRepository
{
    /**
     * Check if entity can be removed (deleted). If not, return an error message.
     *
     * @return null|string
     */
    public function getRemoveErrorMessage(Komponent $komponent)
    {
        $query = $this->_em->createQuery('SELECT d FROM AppBundle:TekniskIsoleringTiltagDetail d WHERE d.komponent = :komponent');
        $query->setParameter('komponent', $komponent);
        $result = $query->getResult();

        if ($result) {
            return 'komponent.error.in_use';
        }

        return null;
    }
}
