<?php

/*
 * This file is part of aaplusplus.
 *
 * (c) 2019 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace AppBundle\Entity\TekniskIsoleringTiltagDetail;

use Doctrine\ORM\EntityRepository;

/**
 * NyttiggjortVarmeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NyttiggjortVarmeRepository extends EntityRepository
{
    /**
     * Check if entity can be removed (deleted). If not, return an error message.
     *
     * @return null|string
     */
    public function getRemoveErrorMessage(NyttiggjortVarme $nyttiggjortVarme)
    {
        $query = $this->_em->createQuery('SELECT d FROM AppBundle:PumpeTiltagDetail d WHERE d.nyttiggjortVarme = :nyttiggjortVarme');
        $query->setParameter('nyttiggjortVarme', $nyttiggjortVarme);
        $result = $query->getResult();

        if ($result) {
            return 'nyttiggjortVarme.error.in_use';
        }

        $query = $this->_em->createQuery('SELECT d FROM AppBundle:TekniskIsoleringTiltagDetail d WHERE d.nyttiggjortVarme = :nyttiggjortVarme');
        $query->setParameter('nyttiggjortVarme', $nyttiggjortVarme);
        $result = $query->getResult();

        if ($result) {
            return 'nyttiggjortVarme.error.in_use';
        }

        return null;
    }
}
