<?php

/*
 * This file is part of aaplusplus.
 *
 * (c) 2019 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{
    const CONFIGURATION_ID = 1;

    public function getConfiguration()
    {
        $entity = $this->find(self::CONFIGURATION_ID);
        if (null === $entity) {
            $entity = new Configuration();
            $entity->setId(self::CONFIGURATION_ID);
            $em = $this->_em;
            $em->persist($entity);
            $em->flush();
        }

        return $entity;
    }
}
