<?php

/*
 * This file is part of aaplusplus.
 *
 * (c) 2019 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SolcelleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolcelleRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['KWp' => 'ASC']);
    }

    /**
     * Find a Solcelle by KWp.
     *
     * Return Solcelle with greatest KWp less than or equal to the specified KWp.
     *
     * @param float $KWp
     *                   The KWp
     *
     * @return null|solcelle
     *                       The Solcelle
     */
    public function findByKWp($KWp)
    {
        // @FIXME: Use DQL for this.
        $items = $this->findBy([], ['KWp' => 'DESC']);
        foreach ($items as $solcelle) {
            if ($solcelle->getKWp() <= $KWp) {
                return $solcelle;
            }
        }

        return null;
    }

    /**
     * Check if entity can be removed (deleted). If not, return an error message.
     *
     * @return null|string
     */
    public function getRemoveErrorMessage(Solcelle $solcelle)
    {
        return null;
    }
}
