#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

dir=$(cd $(dirname "${BASH_SOURCE[0]}")/../ && pwd)

docker-compose --project-directory $dir exec php /var/www/html/bin/console "$@"
